Repository DigitalExcellence/dex-frontend, pull requests merged in 2020-12, with the labels that each got.

#368 Feature/365 redesign project overview
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/modules/highlight/top-highlight-cards/top-highlight-cards.component.html
  src/app/modules/highlight/top-highlight-cards/top-highlight-cards.component.scss
  src/app/modules/project/details/details.component.ts
  src/app/modules/project/overview/overview.component.html
  src/app/modules/project/overview/overview.component.scss
  src/app/modules/project/overview/overview.component.ts
  src/app/modules/project/overview/project/project.component.html
  src/app/modules/project/overview/project/project.component.scss
  src/app/modules/project/overview/project/project.component.ts
  src/app/modules/project/project.module.ts
  src/app/services/file-retriever.service.ts
  src/assets/images/grid-icon.svg
  src/assets/images/list-icon.svg
  src/assets/images/placeholder.png
  src/assets/images/placeholder.svg
  src/styles.scss
Labels: priority

#376 Bugfix/373 tags not hidden in production
  CHANGELOG.md
  src/app/modules/project/details/details.component.html
  src/app/modules/project/overview/project/project.component.html
  src/app/modules/project/overview/project/project.component.ts
Labels: priority

#377 Bugfix/fix overview
  CHANGELOG.md
  src/app/modules/project/overview/overview.component.scss
  src/app/modules/project/overview/project/project.component.html
  src/app/modules/project/overview/project/project.component.scss
Labels: bug, priority

#388 Feature/366 update lighthouse home overview
  CHANGELOG.md
  src/app/components/app-layout/app-layout.component.html
  src/app/components/home/home.component.html
  src/app/modules/project/overview/overview.component.html
Labels: SEO, enhancement

#396 Updated styling for images in quill-view
  CHANGELOG.md
  src/app/modules/project/details/details.component.scss
Labels: bug
