Repository DigitalExcellence/dex-frontend, pull requests merged in 2020-10, with the labels that each got.

#308 Feature/298 seo friendly urls
  CHANGELOG.md
  src/app/modules/highlight/top-highlight-cards/top-highlight-cards.component.html
  src/app/modules/highlight/top-highlight-cards/top-highlight-cards.component.ts
  src/app/modules/project/details/details.component.ts
  src/app/modules/project/overview/overview.component.html
  src/app/modules/project/overview/overview.component.ts
Labels: SEO, enhancement

#301 Bugfix/299 design and consistency improvements
  CHANGELOG.md
  src/app/components/app-layout/app-layout.component.scss
  src/app/components/footer/footer.component.scss
  src/app/components/home/home.component.scss
  src/app/components/not-found/not-found.component.scss
  src/app/modules/account/login/login.component.scss
  src/app/modules/highlight/top-highlight-cards/top-highlight-cards.component.scss
  src/app/modules/project/add/manual/manual.component.scss
  src/app/modules/project/add/source/source.component.html
  src/app/modules/project/add/source/source.component.scss
  src/app/modules/project/details/details.component.scss
  src/app/modules/project/edit/edit.component.scss
  src/app/modules/project/embed/embed.component.scss
  src/app/modules/project/modal-highlight-delete/modal-highlight-delete.component.scss
  src/app/modules/project/modal-highlight/modal-highlight.component.scss
  src/app/modules/project/overview/overview.component.html
  src/app/modules/project/overview/overview.component.scss
  src/assets/images/chevron-down-solid-orange.svg
  src/assets/images/chevron-down-solid.svg
  src/assets/styles/_buttons.scss
  src/assets/styles/_typography.scss
  src/assets/styles/_variables.scss
  src/styles.scss
Labels: bug, design

#312 Feature/deployment
  .github/workflows/production-deployment.yml
  .github/workflows/staging-deployment.yml
  Dockerfile
  package-lock.json
  package.json
  src/app/modules/project/details/details.component.html
Labels: hacktoberfest-accepted

#329 Typo fix: Rename hightlight.ts to highlight.ts
  src/app/models/domain/highlight.ts
  src/app/modules/highlight/top-highlight-cards/top-highlight-cards.component.ts
  src/app/modules/project/details/details.component.ts
  src/app/modules/project/modal-highlight-delete/modal-highlight-delete.component.ts
  src/app/services/highlight.service.ts
  src/app/services/highlightid.service.ts
Labels: bug, hacktoberfest-accepted

#330 Add status badges to README, add a list of links to quickly get started
  README.md
Labels: documentation
