Repository DigitalExcellence/dex-frontend, pull requests merged in 2020-09, with the labels that each got.

#295 Feature/283 page discoverability
  CHANGELOG.md
  angular.json
  src/app/components/app-layout/app-layout.component.html
  src/app/components/home/home.component.html
  src/app/modules/account/login/login.component.html
  src/app/modules/highlight/top-highlight-cards/top-highlight-cards.component.html
  src/app/modules/project/add/source/source.component.html
  src/app/modules/project/details/details.component.html
  src/app/modules/project/embed/embed.component.html
  src/app/modules/project/overview/overview.component.html
  src/index.html
  src/robots.txt
  src/sitemap.xml
Labels: SEO

#305 Feature/286 meta tags update
  CHANGELOG.md
  src/app/components/home/home.component.ts
  src/app/modules/account/login/login.component.ts
  src/app/modules/project/add/manual/manual.component.ts
  src/app/modules/project/add/source/source.component.ts
  src/app/modules/project/details/details.component.ts
  src/app/modules/project/overview/overview.component.ts
  src/app/modules/project/project.module.ts
  src/app/services/seo.service.ts
  src/index.html
Labels: SEO, enhancement

#269 There is no silent-refresh.html, redirect to auth-callback instead
  CHANGELOG.md
  src/app/components/auth-callback/auth-callback.component.ts
  src/app/services/auth.service.ts
  src/assets/oidc-client.min.js
  src/assets/silent-refresh.html
  src/environments/environment.staging.ts
Labels: bug

#303 Bugfix/97 new design illustrations
  CHANGELOG.md
  src/app/components/home/home.component.html
  src/app/components/home/home.component.scss
  src/app/modules/account/login/login.component.html
  src/app/modules/account/login/login.component.scss
  src/assets/images/illustrations/undraw_Access_account_re_8spm.svg
  src/assets/images/illustrations/undraw_mobile_development_8gyo.svg
Labels: bug, design
