Repository DigitalExcellence/dex-frontend, pull requests merged in 2021-04, with the labels that each got.

#447 Bugfix/440 styling fixes project overview
  CHANGELOG.md
  src/app/components/footer/footer.component.scss
  src/app/modules/project/details/details.component.html
  src/app/modules/project/details/details.component.scss
  src/app/modules/project/details/details.component.ts
  src/app/modules/project/overview/overview.component.html
  src/app/modules/project/overview/overview.component.scss
  src/app/modules/project/overview/overview.component.ts
  src/app/modules/project/overview/project/project.component.html
  src/app/modules/project/overview/project/project.component.scss
  src/assets/styles/_variables.scss
Labels: bug, design

#472 471-fix-import-project-without-short-description
  CHANGELOG.md
  src/app/modules/project/add/main/wizard/wizardPages/default/project-link/project-link.component.ts
  src/app/services/wizard.service.ts
Labels: bug

#459 Bugfix/458-edit-and-delete-button-always-shown
  CHANGELOG.md
  src/app/models/domain/scopes.ts
  src/app/modules/project/details/details.component.ts
Labels: bug

#461 Feature/451-add-call-to-action-icons
  CHANGELOG.md
  src/app/config/call-to-action-icons-config.ts
  src/app/models/domain/call-to-action-option.ts
  src/app/models/domain/call-to-action.ts
  src/app/modules/project/add/main/wizard/wizardPages/default/project-call-to-action/project-call-to-action.component.html
  src/app/modules/project/add/main/wizard/wizardPages/default/project-call-to-action/project-call-to-action.component.scss
  src/app/modules/project/details/details.component.html
  src/app/modules/project/details/details.component.ts
  src/app/services/call-to-action-option.service.ts
  src/app/services/project.service.ts
  src/app/services/wizard.service.ts
Labels: requires review
