Repository DigitalExcellence/dex-frontend, pull requests merged in 2021-06, with the labels that each got.

#527 Bugfix/fix homepage
  CHANGELOG.md
  src/app/modules/home/highlight-slider/highlight-slider.component.html
  src/app/modules/home/highlight-slider/highlight-slider.component.scss
  src/styles.scss
Labels: design

#528 Feature/518 relocate buttons details page
  CHANGELOG.md
  src/app/modules/project/details/details.component.html
  src/app/modules/project/details/details.component.scss
Labels: Refactor Friday, requires review

#542 Feature/499 sort projects on likes
  CHANGELOG.md
  src/app/modules/project/overview/overview.component.ts
Labels: Good first issue, requires review
